const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_ITEMS: 'FETCH_ITEMS',
    ADD_ITEM: 'ADD_ITEM',
    FETCH_GEO: 'FETCH_GEO',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE'
}

export default Constants;